M48
; DRILL file {KiCad (6.0.8)} date Tue Apr 18 12:53:02 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-18T12:53:02+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0941
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1358
%
G90
G05
T1
X2.8079Y-1.939
X2.8079Y-2.8331
T2
X3.1358Y-2.5689
X3.1358Y-3.463
X5.3091Y-1.939
X5.3091Y-2.8331
T0
M30
